[
  "",
  "",
  "Org",
  "Line #",
  "Band",
  "Pri #",
  "FLT#",
  "Brief",
  "Line Status",
  "Line Reason",
  "Side #",
  "T/O Time",
  "Model",
  "Act T/O",
  "Dep ICAO",
  "Land Time",
  "Act Land",
  "Dest ICAO",
  "Flt Rec",
  "Plan Dur",
  "Line Dur",
  "Instructor",
  "Student",
  "Sortie #",
  "Event 1",
  "Evt 1 Dur",
  "Event 1 Status",
  "Event 1 Reason",
  "Mod 1",
  "Msn 1",
  "Event 2",
  "Evt 2 Dur",
  "Event 2 Status",
  "Event 2 Reason",
  "Mod 2",
  "Msn 2",
  "Schedule Build Remarks",
  "Schedule Exe Remarks",
  "Call Sign",
  "Maint Remarks",
  "ADB Return",
  "Maint. Rtrn",
  "ADD Reason",
  "A/C Issue Time",
  "Park Spot",
  "A/C Accept Time",
  "SCHED_LINE_ID",
  "Tag"
]